### PR TITLE
Add Some Stuff

### PR DESCRIPTION
**Pull request by franciscoatwi**
- code new aliases
- renew data

### CODE REVIEW

**Comment by Mystifi** [comment]
I'm not sure how I feel about overwriting the aliases; just because they're not needed on PS! main doesn't mean they're not needed here, necessarily. Also, as far as I know, we don't need (?) the actual battle functions themselves; we mainly use the move objects for their names, descriptions, et cetera, so I don't think it's that big of a deal (especially since those moves contain functions this repo doesn't have - again, just copy+pasted for the necessary move metadata).

**Comment by franciscoatwi** [comment]
I mean, the battle functions were there before I pull requested, right? And true, though I didn't think an update on the data would be bad since some of it was updated like a year ago.

**Comment by sirDonovan** [comment]
You can remove the <code>data/</code> changes. I'm working on a way to update those files automatically.

**Comment by franciscoatwi** [comment]
Okay,  I'm going to work on this PR a bit. May take a bit because of stuff irl but i'll get it done.

**Comment by HarmanPC** [comment]
What were you about to do?

**Comment by franciscoatwi** [comment]
Improve general things I noticed could be a tad bit better.

**Pull request closed without merging**
